[project]
name = "filament-tracker"
version = "0.5.0.dev1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Armaan Sandhu", email = "103614886+armaan3722@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.11.0",
    "pandas>=3.0.3",
    "platformdirs>=4.11.0",
    "python-dotenv>=1.2.2",
]

[project.scripts]
filament-tracker = "filament_tracker.main:main"
test-tracker = "filament_tracker.main:get_paths"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pandas-stubs>=3.0.5.260730",
    "ruff>=0.16.1",
    "ty>=0.0.67",
]
